site_name: PantheonLab Documentation
site_description: Documentation complète du lab "PantheonLab"
site_author: PantheonLab Team
site_url: https://pantheonlab.github.io

repo_name: PantheonLab
repo_url: https://github.com/0xbbuddha/pantheonlab
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: brown
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Basculer vers le thème sombre
    - scheme: slate
      primary: brown
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Basculer vers le thème clair
  font:
    text: "Cinzel"
  favicon: assets/images/favicon.png
        
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.arithmatex:
      generic: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

extra_css:
  - assets/stylesheets/extra.css

nav:
  - Accueil: index.md
  - Présentation:
    - Vue d'ensemble: presentation/overview.md
    - Architecture: presentation/architecture.md
    - Thématique: presentation/theme.md
  - Installation:
    - Prérequis: installation/prerequisites.md
    - Installation rapide: installation/quickstart.md
  - Writeup:
    - Introduction: writeup/introduction.md
    - Énumération: writeup/enumeration.md
    - FootHold_Linux: writeup/foothold_linux.md
    - FootHold_Windows: writeup/foothold_windows.md
    - Windows_Privesc: writeup/windows_privesc.md 
    - Linux_Privesc: writeup/linux_privesc_hera.md
    - Conclusion: writeup/conclusion.md
  - Références:
    - Ressources: references/resources.md 
