site_name: PantheonLab Documentation
site_description: Documentation complète du lab de sécurité Active Directory inspiré de la mythologie grecque
site_author: PantheonLab Team
site_url: https://pantheonlab.github.io

repo_name: PantheonLab
repo_url: https://github.com/bbuddha/vulnad
edit_uri: edit/main/docs/

theme:
  name: material
  language: fr
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Basculer vers le thème sombre
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Basculer vers le thème clair
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

nav:
  - Accueil: index.md
  - Présentation:
    - Vue d'ensemble: presentation/overview.md
    - Architecture: presentation/architecture.md
    - Thématique: presentation/theme.md
  - Installation:
    - Prérequis: installation/prerequisites.md
    - Installation rapide: installation/quickstart.md
    - Configuration: installation/configuration.md
    - Déploiement: installation/deployment.md
  - Writeup:
    - Introduction: writeup/introduction.md
    - Énumération: writeup/enumeration.md
    - Exploitation: writeup/exploitation.md
    - Élévation de privilèges: writeup/privesc.md
    - Conclusion: writeup/conclusion.md
  - Références:
    - Commandes utiles: references/commands.md
    - Ressources: references/resources.md 