name: Build MkDocs

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-material-extensions pymdown-extensions paginate mkdocs-git-revision-date-localized-plugin
      - name: Build MkDocs site
        run: mkdocs build 